GET http://localhost:4000/userexist?email=ph.hoangloc@gmail.com
####
POST  http://localhost:4000/sendmailtoacctive
Content-Type: application/json

{
    "email":"ph.hoangloc@gmail.com"
}
###
POST   http://localhost:4000/login
Content-Type: application/json

{
    "username":"hoangloc",
    "password":"123456"
}
###

GET http://localhost:4000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZmVhZWQ3YzE1NGNjNDgyYzRhMzM5NSIsImlhdCI6MTY5Mjg1NTcwMywiZXhwIjoxNjkyOTQyMTAzfQ.XjlfMaeb0JpvAJP331HmETxFFQEff_hW29w0FDOKIBI
Content-Type: application/json
###
Post http://localhost:4000/user/blog/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDM1OWEyMDAwODBjZDZmMzE1NWM2MCIsImlhdCI6MTY5MjY3MTgyOCwiZXhwIjoxNjkyNzU4MjI4fQ.NqvPUyPbwD_njQxig-5rD6FR_Okr1YXL7GJMt0AD78Y
Content-Type: application/json

{
    "title":"blog2",
    "slug":"blog2",
    "detail":"this is new blog2"
}
###
Put http://localhost:4000/user/id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZmVhZWQ3YzE1NGNjNDgyYzRhMzM5NSIsImlhdCI6MTY5Mjg1NTcwMywiZXhwIjoxNjkyOTQyMTAzfQ.XjlfMaeb0JpvAJP331HmETxFFQEff_hW29w0FDOKIBI
Content-Type: application/json

{
    "info":
    {
    "address":"OSAKA",
    "fullname":"Pham Hoang Loc",
    "phone": "08095113499"
    }
}
###
DELETE   http://localhost:4000/user/blog/64e425da99ebe2d40fb44e4a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDM1OWEyMDAwODBjZDZmMzE1NWM2MCIsImlhdCI6MTY5MjY3MTgyOCwiZXhwIjoxNjkyNzU4MjI4fQ.NqvPUyPbwD_njQxig-5rD6FR_Okr1YXL7GJMt0AD78Y
###
